Repository LLK/scratch-paint, pull requests merged in 2018-08, with the labels that each got.

#572 Selection limit
  src/helper/bitmap.js
  src/helper/selection-tools/selection-box-tool.js
Labels: pr - good to merge

#573 Localize tool tooltips
  src/components/bit-brush-mode/bit-brush-mode.jsx
  src/components/bit-eraser-mode/bit-eraser-mode.jsx
  src/components/bit-fill-mode/bit-fill-mode.jsx
  src/components/bit-line-mode/bit-line-mode.jsx
  src/components/bit-oval-mode/bit-oval-mode.jsx
  src/components/bit-rect-mode/bit-rect-mode.jsx
  src/components/bit-select-mode/bit-select-mode.jsx
  src/components/bit-text-mode/bit-text-mode.jsx
  src/components/brush-mode/brush-mode.jsx
  src/components/eraser-mode/eraser-mode.jsx
  src/components/fill-mode/fill-mode.jsx
  src/components/line-mode/line-mode.jsx
  src/components/oval-mode/oval-mode.jsx
  src/components/rect-mode/rect-mode.jsx
  src/components/reshape-mode/reshape-mode.jsx
  src/components/rounded-rect-mode/rounded-rect-mode.jsx
  src/components/select-mode/select-mode.jsx
  src/components/text-mode/text-mode.jsx
  src/lib/messages.js
Labels: pr - good to merge

#382 Loupe issues fixed #378
  package.json
  src/components/loupe/loupe.jsx
  src/components/paint-editor/paint-editor.css
  src/containers/paint-editor.jsx
  src/helper/layer.js
  src/helper/tools/eye-dropper.js
Labels: pr - needs review

#597 Reduce hit tolerance
  src/helper/bit-tools/oval-tool.js
  src/helper/bit-tools/rect-tool.js
  src/helper/bit-tools/select-tool.js
  src/helper/selection-tools/reshape-tool.js
  src/helper/selection-tools/select-tool.js
  src/helper/tools/oval-tool.js
  src/helper/tools/rect-tool.js
  src/helper/tools/text-tool.js
Labels: pr - good to merge

#602 Scrollbars
  src/components/paint-editor/paint-editor.css
  src/components/paint-editor/paint-editor.jsx
  src/components/scrollable-canvas/scrollable-canvas.css
  src/components/scrollable-canvas/scrollable-canvas.jsx
  src/containers/paint-editor.jsx
  src/containers/paper-canvas.css
  src/containers/paper-canvas.jsx
  src/containers/scrollable-canvas.jsx
  src/helper/view.js
  src/reducers/selected-items.js
Labels: pr - good to merge

#616 Mirror margins, borders and arrow icons for RTL
  src/components/color-button/color-button.css
  src/components/dropdown/dropdown.css
  src/components/fixed-tools/fixed-tools.css
  src/components/fixed-tools/fixed-tools.jsx
  src/components/forms/label.css
  src/components/input-group/input-group.css
  src/components/mode-tools/mode-tools.css
  src/components/paint-editor/paint-editor.css
  src/components/paint-editor/paint-editor.jsx
Labels: pr - good to merge

#617 Make PaintEditor component rtl aware
  src/components/color-picker/color-picker.css
  src/components/color-picker/color-picker.jsx
  src/components/fixed-tools/fixed-tools.css
  src/components/fixed-tools/fixed-tools.jsx
  src/components/input-group/input-group.jsx
  src/components/paint-editor/paint-editor.jsx
  src/containers/color-picker.jsx
  src/containers/paint-editor.jsx
  src/reducers/layout.js
  src/reducers/scratch-paint-reducer.js
Labels: localization, pr - good to merge

#623 Keyboard shortcuts
  package.json
  src/components/mode-tools/mode-tools.jsx
  src/containers/copy-paste-hoc.jsx
  src/containers/font-dropdown.jsx
  src/containers/mode-tools.jsx
  src/containers/paint-editor.jsx
  src/containers/paper-canvas.jsx
  src/helper/bitmap.js
  src/helper/selection.js
  src/index.js
Labels: pr - good to merge

#630 Scroll containers shouldn't intercept pointer events
  src/components/scrollable-canvas/scrollable-canvas.jsx
Labels: pr - good to merge

#633 Hocs
  src/components/paint-editor/paint-editor.jsx
  src/containers/fixed-tools.jsx
  src/containers/mode-tools.jsx
  src/containers/paint-editor.jsx
  src/helper/bitmap.js
  src/hocs/copy-paste-hoc.jsx
  src/hocs/keyboard-shortcuts-hoc.jsx
  src/hocs/selection-hoc.jsx
  src/hocs/undo-hoc.jsx
  src/hocs/update-image-hoc.jsx
Labels: pr - good to merge

#629 Zoom to fit
  README.md
  src/components/paint-editor/paint-editor.jsx
  src/containers/paint-editor.jsx
  src/containers/paper-canvas.jsx
  src/helper/view.js
  src/reducers/scratch-paint-reducer.js
  src/reducers/zoom-levels.js
Labels: pr - good to merge

#642 Disable keyboard shortcuts for now
  src/hocs/keyboard-shortcuts-hoc.jsx
Labels: pr - needs review
