Repository LLK/scratch-paint, pull requests merged in 2018-09, with the labels that each got.

#634 Copy and delete work on all objects when none are selected
  src/components/mode-tools/mode-tools.jsx
  src/containers/mode-tools.jsx
  src/helper/bitmap.js
  src/hocs/copy-paste-hoc.jsx
Labels: pr - good to merge

#645 Make gradient icons not selectable
  src/components/color-picker/color-picker.css
Labels: pr - needs review

#651 Rtl text tool
  src/containers/text-mode.jsx
  src/helper/tools/text-tool.js
  src/playground/playground.jsx
Labels: pr - good to merge

#654 Re-enable keyboard shortcuts
  src/hocs/keyboard-shortcuts-hoc.jsx
Labels: pr - needs review

#657 Unmount deactivate
  src/components/paint-editor/paint-editor.css
  src/components/paint-editor/paint-editor.jsx
  src/containers/bit-brush-mode.jsx
  src/containers/bit-eraser-mode.jsx
  src/containers/bit-fill-mode.jsx
  src/containers/bit-line-mode.jsx
  src/containers/bit-oval-mode.jsx
  src/containers/bit-rect-mode.jsx
  src/containers/bit-select-mode.jsx
  src/containers/brush-mode.jsx
  src/containers/eraser-mode.jsx
  src/containers/fill-mode.jsx
  src/containers/line-mode.jsx
  src/containers/oval-mode.jsx
  src/containers/rect-mode.jsx
  src/containers/reshape-mode.jsx
  src/containers/rounded-rect-mode.jsx
  src/containers/select-mode.jsx
  src/containers/text-mode.jsx
Labels: pr - good to merge

#673 Use RGBA instead of hex so Edge can understand the color
  src/components/scrollable-canvas/scrollable-canvas.css
Labels: pr - good to merge

#671 Fence tools to make it less easy to lose work off the sides
  src/helper/selection-tools/move-tool.js
  src/helper/selection-tools/nudge-tool.js
  src/helper/selection-tools/point-tool.js
  src/helper/selection-tools/scale-tool.js
Labels: pr - needs review

#662 Export bit shapes
  src/helper/bit-tools/oval-tool.js
  src/helper/bit-tools/rect-tool.js
  src/helper/bitmap.js
  src/hocs/update-image-hoc.jsx
Labels: pr - needs review

#682 Add safety checks to fill and stroke colors
  src/helper/bitmap.js
Labels: pr - good to merge

#680 Export bit text
  src/hocs/update-image-hoc.jsx
Labels: pr - needs review

#678 Bitmap select state
  src/containers/bit-oval-mode.jsx
  src/containers/bit-rect-mode.jsx
  src/containers/paper-canvas.jsx
  src/helper/bit-tools/oval-tool.js
  src/helper/bit-tools/rect-tool.js
  src/helper/bit-tools/select-tool.js
  src/helper/undo.js
  src/reducers/fill-bitmap-shapes.js
Labels: pr - needs review

#681 Switch fix aspect ratio to default when resizing by a corner
  src/helper/selection-tools/scale-tool.js
Labels: pr - needs review

#679 Don't navigate away when paint editor is open and delete/backspace are pressed
  src/hocs/keyboard-shortcuts-hoc.jsx
Labels: pr - good to merge

#685 Don't scale text outlines
  src/helper/math.js
Labels: pr - good to merge

#696 Save after adding points
  src/helper/selection-tools/reshape-tool.js
Labels: pr - good to merge

#689 Use consistent hit testing
  src/helper/hover.js
  src/helper/selection-tools/reshape-tool.js
Labels: pr - needs review

#695 Make stroke width 0 when transparent
  src/containers/stroke-color-indicator.jsx
  src/containers/stroke-width-indicator.jsx
  src/helper/style-path.js
  src/reducers/stroke-color.js
  src/reducers/stroke-width.js
  test/unit/stroke-color-reducer.test.js
  test/unit/stroke-width-reducer.test.js
Labels: pr - good to merge

#705 Add Gaidhlig (gd) to the ‘hide-label’ locales
  src/lib/hide-label.js
Labels: localization, pr - good to merge
