Repository LLK/scratch-paint, pull requests merged in 2018-07, with the labels that each got.

#542 Increase selected tool visibility by making the icon white and bg blue.
  src/components/tool-select-base/tool-select-base.css
Labels: pr - good to merge

#547 Fix reshape
  src/helper/selection-tools/reshape-tool.js
Labels: pr - good to merge

#545 Delete button
  src/components/forms/label.css
  src/components/mode-tools/icons/delete.svg
  src/components/mode-tools/mode-tools.jsx
  src/containers/mode-tools.jsx
Labels: pr - good to merge

#549 Correct the view bounds when the paper canvas is initialized.
  src/containers/paper-canvas.jsx
Labels: pr - good to merge

#551 Update image when deleting points
  src/helper/selection-tools/point-tool.js
Labels: pr - good to merge

#553 Make the bitmap/vector conversion button look enabled
  src/components/paint-editor/paint-editor.css
Labels: pr - good to merge

#550 Draw oval and rectangle outlines in bitmap
  src/components/bit-oval-mode/oval-outlined.svg
  src/components/bit-rect-mode/rectangle-outlined.svg
  src/components/button/button.css
  src/components/button/button.jsx
  src/components/labeled-icon-button/labeled-icon-button.jsx
  src/components/mode-tools/mode-tools.jsx
  src/containers/bit-oval-mode.jsx
  src/containers/bit-rect-mode.jsx
  src/containers/fill-color-indicator.jsx
  src/containers/mode-tools.jsx
  src/containers/oval-mode.jsx
  src/containers/paint-editor.jsx
  src/containers/paper-canvas.jsx
  src/containers/rect-mode.jsx
  src/containers/reshape-mode.jsx
  src/containers/rounded-rect-mode.jsx
  src/containers/select-mode.jsx
  src/containers/stroke-color-indicator.jsx
  src/containers/text-mode.jsx
  src/helper/bit-tools/oval-tool.js
  src/helper/bit-tools/rect-tool.js
  src/helper/bitmap.js
  src/helper/style-path.js
  src/reducers/bit-brush-size.js
  src/reducers/fill-bitmap-shapes.js
  src/reducers/fill-color.js
  src/reducers/scratch-paint-reducer.js
  src/reducers/selected-items.js
  src/reducers/stroke-color.js
  src/reducers/stroke-width.js
Labels: pr - good to merge

#559 Bitmap gradient
  src/containers/bit-fill-mode.jsx
  src/containers/fill-color-indicator.jsx
  src/helper/bit-tools/fill-tool.js
  src/helper/bitmap.js
  src/helper/style-path.js
  src/helper/tools/fill-tool.js
Labels: blocked, pr - needs review

#569 Save bitmap selection
  src/containers/paint-editor.jsx
  src/helper/bit-tools/select-tool.js
  src/helper/bitmap.js
  src/helper/undo.js
Labels: pr - needs review
