Repository LLK/scratch-paint, pull requests merged in 2018-04, with the labels that each got.

#264 Use sans-serif font in playground
  src/playground/index.ejs
Labels: pr - needs work

#339 Fix editorconfig indentation rules
  .editorconfig
  src/playground/index.ejs
Labels: pr - good to merge

#337 Reduce target when fill hole with same color #301
  src/helper/group.js
  src/helper/tools/fill-tool.js
Labels: pr - needs work

#359 Issue/332 Rotate-tool fix
  src/helper/selection-tools/rotate-tool.js
Labels: pr - needs work

#367 Fix text nudge
  src/helper/tools/text-tool.js
Labels: pr - good to merge

#356 Bring back eraser after snapshot
  src/helper/blob-tools/blob.js
Labels: pr - needs review

#368 Replace png background with vector version (for #155)
  src/helper/background.png
  src/helper/layer.js
Labels: pr - good to merge

#369 Make sure to remove the bounding box when no items are selected
  src/helper/selection-tools/bounding-box-tool.js
Labels: pr - good to merge

#360 Add ability to fill transparent text
  package.json
  src/helper/tools/fill-tool.js
Labels: pr - good to merge

#374 Convert to bitmap shape rendering
  src/containers/paper-canvas.jsx
Labels: pr - needs review

#383 Escape end text edit mode #366
  src/helper/tools/text-tool.js
Labels: pr - good to merge

#387 Bitmap brush
  src/components/bit-brush-mode/bit-brush-mode.jsx
  src/components/bit-brush-mode/brush.svg
  src/components/mode-tools/mode-tools.jsx
  src/components/paint-editor/paint-editor.jsx
  src/containers/bit-brush-mode.jsx
  src/containers/brush-mode.jsx
  src/containers/paint-editor.jsx
  src/helper/bit-tools/brush-tool.js
  src/helper/bitmap.js
  src/helper/layer.js
  src/lib/modes.js
  src/reducers/bit-brush-size.js
  src/reducers/scratch-paint-reducer.js
Labels: pr - good to merge

#386 Double resolution of canvas
  src/containers/paint-editor.jsx
  src/containers/paper-canvas.jsx
  src/helper/layer.js
  src/helper/math.js
  src/helper/transparent.png
  src/helper/view.js
  src/reducers/brush-mode.js
  src/reducers/eraser-mode.js
  src/reducers/stroke-width.js
Labels: pr - good to merge

#407 Remove ungroup on import
  src/containers/paper-canvas.jsx
Labels: pr - good to merge

#404 Import and export bitmaps
  README.md
  src/components/paint-editor/paint-editor.jsx
  src/containers/bit-brush-mode.jsx
  src/containers/bit-line-mode.jsx
  src/containers/brush-mode.jsx
  src/containers/eraser-mode.jsx
  src/containers/fill-color-indicator.jsx
  src/containers/fill-mode.jsx
  src/containers/line-mode.jsx
  src/containers/mode-tools.jsx
  src/containers/oval-mode.jsx
  src/containers/paint-editor.jsx
  src/containers/paper-canvas.jsx
  src/containers/rect-mode.jsx
  src/containers/reshape-mode.jsx
  src/containers/rounded-rect-mode.jsx
  src/containers/select-mode.jsx
  src/containers/stroke-color-indicator.jsx
  src/containers/stroke-width-indicator.jsx
  src/containers/text-mode.jsx
  src/helper/bit-tools/brush-tool.js
  src/helper/bit-tools/line-tool.js
  src/helper/blob-tools/blob.js
  src/helper/group.js
  src/helper/order.js
  src/helper/selection-tools/bounding-box-tool.js
  src/helper/selection-tools/handle-tool.js
  src/helper/selection-tools/move-tool.js
  src/helper/selection-tools/nudge-tool.js
  src/helper/selection-tools/point-tool.js
  src/helper/selection-tools/reshape-tool.js
  src/helper/selection-tools/rotate-tool.js
  src/helper/selection-tools/scale-tool.js
  src/helper/selection-tools/select-tool.js
  src/helper/selection.js
  src/helper/tools/fill-tool.js
  src/helper/tools/oval-tool.js
  src/helper/tools/rect-tool.js
  src/helper/tools/rounded-rect-tool.js
  src/helper/tools/text-tool.js
  src/helper/undo.js
  src/playground/playground.jsx
  src/reducers/format.js
  test/unit/format-reducer.test.js
Labels: pr - good to merge
